{% set version = "1.42.0" %}
{% set name = "grpcio-tools" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d0a0daa82eb2c2fb8e12b82a458d1b7c5516fe1135551da92b1a02e2cba93422
  patches:
    - 0001-Monkey-patch-distutils.ccompiler.spawn-to-elide-std-.patch

build:
  number: 1
  missing_dso_whitelist:  # [s390x]
    - $RPATH/ld64.so.1    # [s390x]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch       # [not win]
    - m2-patch    # [win]
 
  host:
    - grpcio =={{ version }}
    - pip
    - setuptools
    - wheel
    - protobuf 3.20.3
    - python
  run:
    - grpcio =={{ version }}
    - protobuf >=3.6.0
    - python

test:
  requires:
    - pip
  imports:
    - grpc_tools
  commands:
    - pip check

about:
  home: https://grpc.io
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Protobuf code generator for gRPC
  description: Various tools for use with gRPC
  doc_url: https://grpc.io/docs/
  dev_url: https://github.com/grpc/grpc/tree/master/tools

extra:
  recipe-maintainers:
    - martinRenou
