{% set version = "1.62.2" %}
{% set name = "grpcio-tools" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5fd5e1582b678e6b941ee5f5809340be5e0724691df5299aae8226640f94e18f
  # more work required to unvendor win - to be done in later update.
  patches:                          # [not win]
   - unvendor_abseil_protobuf.patch # [not win]

build:
  skip: true  # [py<37]
  number: 0
  missing_dso_whitelist:  # [s390x]
    - $RPATH/ld64.so.1    # [s390x]
  ignore_run_exports:
    # The only abseil type used directly is absl::string_view 
    # which is an alias to std::string_view in our case.
    # Since libabseil is built with ABSL_OPTION_USE_STD_STRING_VIEW.
    # Revisit on grpcio-tools updates.
    - libabseil

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch # [unix]
    - m2-patch # [win]
  host:
    - pip
    - setuptools
    - wheel
    - python
    - cython
    - libabseil 20240116.2
    - libprotobuf 4.25.3
  run:
    - grpcio >={{ version }}
    - protobuf >=4.21.6,<5.0a0
    - setuptools
    - python
    # through run_exports
    - libprotobuf

test:
  requires:
    - pip
  imports:
    - grpc_tools
    - grpc_tools.protoc
    - grpc_tools.command
  commands:
    - pip check

about:
  home: https://grpc.io
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Protobuf code generator for gRPC
  description: Various tools for use with gRPC
  doc_url: https://grpc.io/docs/
  dev_url: https://github.com/grpc/grpc/tree/master/tools/distrib/python/grpcio_tools

extra:
  recipe-maintainers:
    - martinRenou
